# -*- coding: utf-8 -*-
# Generated by Django 1.9.3 on 2016-05-13 11:08
from __future__ import unicode_literals

import ccompiler.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CProgram',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('code_file', models.FileField(blank=True, help_text='Allowed type - .c, .h', upload_to=ccompiler.models.file_name)),
                ('created', models.DateTimeField(editable=False)),
                ('modified', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
