# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 05:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrcompiler', '0002_delete_test'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyprogram',
            name='id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
