# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 01:26
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('avrcompiler', '0003_auto_20151208_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='assemblyprogram',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2015, 12, 11, 1, 26, 37, 432067, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='assemblyprogram',
            name='modified',
            field=models.DateField(),
        ),
    ]
