# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-11 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('avrcompiler', '0004_auto_20151210_1926'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assemblyprogram',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='assemblyprogram',
            name='modified',
            field=models.DateTimeField(),
        ),
    ]
